import Head from 'next/head'
import Games from '../components/Games'
import Pilihan from '../components/Pilihan'
import Promo from '../components/Promo'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Promo/>
      <Pilihan/>
      <Games/>
    </div>
  )
}