import Head from 'next/head'
import Hitungwinrate from '../components/Hitungwinrate'


export default function Pagehitungwinrate() {
  return (
    <div>
        <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hitungwinrate/>
    </div>
  )
}