import Head from 'next/head'
import Pilihan from '../components/Pilihan'
import Promo from '../components/Promo'
import Voucher from '../components/Voucher'

export default function Pagepromo() {
  return (
    <div>
        <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Promo/>
        <Pilihan/>
        <Voucher/>
    </div>
  )
}