import Head from 'next/head'
import Aboutus from '../components/Aboutus'

export default function Pageaboutus() {
  return (
    <div>
    <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Aboutus/>
    </div>
  )
}