import Head from 'next/head'
import Periksapesanan from '../components/Periksapesanan'


export default function Pageperiksapesanan() {
  return (
    <div>
        <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Periksapesanan/>
    </div>
  )
}