import Head from 'next/head'
import Signup from '../components/Signup'


export default function Signuppage() {
  return (
    <div>
        <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Signup/>
    </div>
  )
}