import Head from 'next/head'
import Signin from '../components/Signin'


export default function Signinpage() {
  return (
    <div>
        <Head>
        <title>CORRIDOR AJA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Signin/>
    </div>
  )
}